### ISSUE TITLE
Problem with plugin installation on DI server

### ISSUE THREAD

**Issue by mayolika** [maasdi/pentaho-mongodb-delete-plugin#1]
Hi,

I am running Enterprise Version of PDI 5.4.  I installed plugin on my local machine and on server following instruction for manual installation.  When I create a transformation and run it locally everything is perfect.  When I try to run it on remote server I have exception:
There was an error passing the exported transformation to the remote server: 
org.pentaho.di.core.exception.KettleMissingPluginsException: 
Missing plugins found while loading a transformation

Step : MongoDbDelete
	at org.pentaho.di.trans.TransMeta.loadXML(TransMeta.java:2882)
	at org.pentaho.di.trans.TransMeta.<init>(TransMeta.java:2718)
	at org.pentaho.di.trans.TransMeta.<init>(TransMeta.java:2670)
	at org.pentaho.di.trans.TransMeta.<init>(TransMeta.java:2647)
	at org.pentaho.di.trans.TransMeta.<init>(TransMeta.java:2627)
	at org.pentaho.di.trans.TransMeta.<init>(TransMeta.java:2608)
	at org.pentaho.di.www.RegisterPackageServlet.generateBody(RegisterPackageServlet.java:100)
	at org.pentaho.di.www.BodyHttpServlet.doGet(BodyHttpServlet.java:73)
	at org.pentaho.di.www.CarteServlet.doGet(CarteServlet.java:72)
	at com.pentaho.pdi.www.RoleBoundCarteServlet.doGet(SourceFile:65)
	at org.pentaho.di.www.CarteServlet.doPost(CarteServlet.java:61)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:643)

thank you,
Irina

**Comment by maasdi** [comment]
Hi Irina,

This happen usually because you start your remote server before MongoDB Delete plugin installed in your PDI.

After installing MongoDB Delete Plugin, you have to restart your remote server so the new installed plugin will initialized on remote server. This should solved your issue.

**Comment by mayolika** [comment]
HI,

I did restarted my remote server twice with no success :(

**Comment by maasdi** [comment]
Are you sure you installed MongoDB delete plugin on your remote server ?

I assume you have two pentaho installations, one on your local and one on your remote server machine. Technically if you install both correctly then should work.

**Comment by mayolika** [comment]
yes, I did.
![screen shot 2015-10-22 at 9 46 51 am](https://cloud.githubusercontent.com/assets/8028597/10666703/4c80a0b4-78a1-11e5-8646-5eb459f09d64.png)

**Comment by mayolika** [comment]
I downloaded file, unzipped it locally and ftp the whole folder to the ../steps directory.  Then I restarted the server, but it didn't work.  Then I put the directory under ../plugins directory, restarted again, but it didn't work either :(  Run out of my option as of now.

**Comment by maasdi** [comment]
Maybe you can try log on to your remote server and run your transformation locally.
Since works fine locally, I don't think plugin problem.

pentaho-mongodb-delete-plugin folder and all contents must be inside steps folder, after ftp the whole folder to your remote server also check permissions.
