### ISSUE TITLE
Unable to connect with mongo

### ISSUE THREAD

**Issue by MuhammadAdeelUsman** [maasdi/pentaho-mongodb-delete-plugin#7]
Hi Guys, 
i'm trying to remove all record from my mongo collection. but mongo delete plugin giving me connection error. Same connection credential working in mongo input and output step.Difference between mongo input and delete plungin is mongo delete plungin option don't have option authenticated database.
we got following error 
Invalid database name format. Database name is either empty or it contains spaces.
detail of error is here can anybody help to solve this

org.pentaho.di.core.exception.KettleException: 
java.lang.IllegalArgumentException: Invalid database name format. Database name is either empty or it contains spaces.
Invalid database name format. Database name is either empty or it contains spaces.

	at com.github.maasdi.mongo.wrapper.NoAuthMongoClientWrapper.getDatabaseNames(NoAuthMongoClientWrapper.java:374)
	at com.github.maasdi.di.trans.steps.mongodbdelete.MongoDbDeleteDialog.setupDBNames(MongoDbDeleteDialog.java:974)
	at com.github.maasdi.di.trans.steps.mongodbdelete.MongoDbDeleteDialog.access$1500(MongoDbDeleteDialog.java:83)
	at com.github.maasdi.di.trans.steps.mongodbdelete.MongoDbDeleteDialog$10.widgetSelected(MongoDbDeleteDialog.java:470)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at com.github.maasdi.di.trans.steps.mongodbdelete.MongoDbDeleteDialog.open(MongoDbDeleteDialog.java:911)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:120)
	at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:8949)
	at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:3291)
	at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:785)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.trans.steps.mongodbinput.MongoDbInputDialog.open(MongoDbInputDialog.java:1091)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:120)
	at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:8949)
	at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:3291)
	at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:785)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.trans.steps.mongodbinput.MongoDbInputDialog.open(MongoDbInputDialog.java:1091)
	at org.pentaho.di.ui.spoon.delegates.SpoonStepsDelegate.editStep(SpoonStepsDelegate.java:120)
	at org.pentaho.di.ui.spoon.Spoon.editStep(Spoon.java:8949)
	at org.pentaho.di.ui.spoon.trans.TransGraph.editStep(TransGraph.java:3291)
	at org.pentaho.di.ui.spoon.trans.TransGraph.mouseDoubleClick(TransGraph.java:785)
	at org.eclipse.swt.widgets.TypedListener.handleEvent(Unknown Source)
	at org.eclipse.swt.widgets.EventTable.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Widget.sendEvent(Unknown Source)
	at org.eclipse.swt.widgets.Display.runDeferredEvents(Unknown Source)
	at org.eclipse.swt.widgets.Display.readAndDispatch(Unknown Source)
	at org.pentaho.di.ui.spoon.Spoon.readAndDispatch(Spoon.java:1375)
	at org.pentaho.di.ui.spoon.Spoon.waitForDispose(Spoon.java:8104)
	at org.pentaho.di.ui.spoon.Spoon.start(Spoon.java:9466)
	at org.pentaho.di.ui.spoon.Spoon.main(Spoon.java:701)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.pentaho.commons.launcher.Launcher.main(Launcher.java:92)
Caused by: java.lang.IllegalArgumentException: Invalid database name format. Database name is either empty or it contains spaces.
	at com.mongodb.DB.<init>(DB.java:67)
	at com.mongodb.DBApiLayer.<init>(DBApiLayer.java:58)
	at com.mongodb.Mongo.getDB(Mongo.java:344)
	at com.mongodb.DBPort$SaslAuthenticator.getDatabase(DBPort.java:928)
	at com.mongodb.DBPort$SaslAuthenticator.sendSaslStart(DBPort.java:935)
	at com.mongodb.DBPort$SaslAuthenticator.authenticate(DBPort.java:898)
	at com.mongodb.DBPort.authenticate(DBPort.java:432)
	at com.mongodb.DBPort.checkAuth(DBPort.java:443)
	at com.mongodb.DBTCPConnector.innerCall(DBTCPConnector.java:293)
	at com.mongodb.DBTCPConnector.call(DBTCPConnector.java:273)
	at com.mongodb.DBCollectionImpl.find(DBCollectionImpl.java:84)
	at com.mongodb.DB.command(DB.java:320)
	at com.mongodb.DB.command(DB.java:299)
	at com.mongodb.DB.command(DB.java:374)
	at com.mongodb.Mongo.getDatabaseNames(Mongo.java:373)
	at com.github.maasdi.mongo.wrapper.NoAuthMongoClientWrapper.getDatabaseNames(NoAuthMongoClientWrapper.java:369)
	... 51 more

**Comment by guoyiwu** [comment]
I solved the issue and updated the branch.you can get latest code from the branch.any question.pls contact me by email(15144186@qq.com).

**Comment by maasdi** [comment]
This issue has been resolved, thanks to Yiwu.
As of now, you need to do manual installation (Please follow the instructions at the main page) until my pull request to pentaho marketplace to update request  merged.
